// This class is generated by Hummingbird Test Framework
// Hummingbird.TestFramework, A product of Hummingbird ALM tool set
// Hummingbird.TestManager, A product of Hummingbird ALM tool set
// Copyright (c) 2014-2017 Huaxing YUAN, All rights reserved
// Copyright (c) Huaxing YUAN
// Template created at: 2017-8-22  21:05 by Huaxing YUAN
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

// General Information about an assembly is controlled through the following 
// set of attributes. Change these attribute values to modify the information
// associated with an assembly.
[assembly: AssemblyTitle("Hummingbird.PetStore")]
[assembly: AssemblyDescription("Extension to test REST API using Swagger")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("Huaxing YUAN")]
[assembly: AssemblyProduct("My Extension")]
[assembly: AssemblyCopyright("Copyright 2018 Huaxing YUAN, All rights reserved.")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]

// Setting ComVisible to false makes the types in this assembly not visible 
// to COM components.  If you need to access a type in this assembly from 
// COM, set the ComVisible attribute to true on that type.
[assembly: ComVisible(false)]

// The following GUID is for the ID of the typelib if this project is exposed to COM
[assembly: Guid("2fbd3e63-45d3-4688-8f33-88ae0b5df9be")]

// Version information for an assembly consists of the following four values:
//
//      Major Version
//      Minor Version 
//      Build Number
//      Revision
//
// You can specify all the values or you can default the Build and Revision Numbers 
// by using the '*' as shown below:
// [assembly: AssemblyVersion("1.0.*")]
[assembly: AssemblyVersion("1.1.*")]
