// This class is generated by Hummingbird Test Framework
// Hummingbird.TestFramework, A product of Hummingbird ALM tool set
// Hummingbird.TestManager, A product of Hummingbird ALM tool set
// Copyright (c) 2014-2018 Huaxing YUAN, All rights reserved
// Template created at: 2018-09-28 00:38 by Huaxing YUAN
using Hummingbird.TestFramework.Extensibility;
using Hummingbird.TestFramework.ExtensionProject;
using Hummingbird.TestFramework.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.ServiceModel;
using System.ServiceModel.Channels;
using System.Text;
using System.Threading.Tasks;

namespace Hummingbird.PetStore
{
	public class MyHttpServiceExtension : HttpServiceExtension
	{

		public override HttpRequestMetadata[] HttpRequestServices
		{
			get
			{
				return new HttpRequestMetadata[]
				{

                new HttpRequestMetadata(){
                    HttpMethod = HttpMethod.POST,
                    Id = new Guid("19139641-475f-380b-6e58-4a6e7001f451"),
                    ContentType = "application/json",
                    Description = "Add a new pet to the store",
                    HttpVersion = Hummingbird.TestFramework.Services.HttpVersion.Version11,
                    OperationName = "addPet",
                    RequestType = typeof(Hummingbird.PetStore.Pet_Store.Pet_Store.addPet),
                    UriTemplate = "https://petstore.swagger.io/v2",
                    Path = "/pet",
                    ApplicationName = "Pet Store",
                    BodySerializer = Hummingbird.TestFramework.Serialization.AbstractSerializer.GetInstance(typeof(Hummingbird.TestFramework.Serialization.JsonSerializer)),
                    ServiceCategory = "Pet Store",
                    ServiceName = "pet",
                    
                },

                new HttpRequestMetadata(){
                    HttpMethod = HttpMethod.PUT,
                    Id = new Guid("1a372ac9-62fa-5e9c-7e12-252781730ced"),
                    ContentType = "application/json",
                    Description = "Update an existing pet",
                    HttpVersion = Hummingbird.TestFramework.Services.HttpVersion.Version11,
                    OperationName = "updatePet",
                    RequestType = typeof(Hummingbird.PetStore.Pet_Store.Pet_Store.updatePet),
                    UriTemplate = "https://petstore.swagger.io/v2",
                    Path = "/pet",
                    ApplicationName = "Pet Store",
                    BodySerializer = Hummingbird.TestFramework.Serialization.AbstractSerializer.GetInstance(typeof(Hummingbird.TestFramework.Serialization.JsonSerializer)),
                    ServiceCategory = "Pet Store",
                    ServiceName = "pet",
                    
                },

                new HttpRequestMetadata(){
                    HttpMethod = HttpMethod.GET,
                    Id = new Guid("04aaec70-57ea-7bfe-554a-a3e7fc49abe6"),
                    ContentType = "application/json",
                    Description = "Finds Pets by status",
                    HttpVersion = Hummingbird.TestFramework.Services.HttpVersion.Version11,
                    OperationName = "findPetsByStatus",
                    RequestType = typeof(Hummingbird.PetStore.Pet_Store.Pet_Store.findPetsByStatus),
                    UriTemplate = "https://petstore.swagger.io/v2",
                    Path = "/pet/findByStatus",
                    ApplicationName = "Pet Store",
                    BodySerializer = Hummingbird.TestFramework.Serialization.AbstractSerializer.GetInstance(typeof(Hummingbird.TestFramework.Serialization.JsonSerializer)),
                    ServiceCategory = "Pet Store",
                    ServiceName = "pet",
                    ResponseType = typeof(Hummingbird.PetStore.Pet_Store.Pet_Store.findPetsByStatus_200),

                },

                new HttpRequestMetadata(){
                    HttpMethod = HttpMethod.GET,
                    Id = new Guid("0330ee22-5109-4b69-fc88-735f8de2be9a"),
                    ContentType = "application/json",
                    Description = "Finds Pets by tags",
                    HttpVersion = Hummingbird.TestFramework.Services.HttpVersion.Version11,
                    OperationName = "findPetsByTags",
                    RequestType = typeof(Hummingbird.PetStore.Pet_Store.Pet_Store.findPetsByTags),
                    UriTemplate = "https://petstore.swagger.io/v2",
                    Path = "/pet/findByTags",
                    ApplicationName = "Pet Store",
                    BodySerializer = Hummingbird.TestFramework.Serialization.AbstractSerializer.GetInstance(typeof(Hummingbird.TestFramework.Serialization.JsonSerializer)),
                    ServiceCategory = "Pet Store",
                    ServiceName = "pet",
                    ResponseType = typeof(Hummingbird.PetStore.Pet_Store.Pet_Store.findPetsByTags_200),

                },

                new HttpRequestMetadata(){
                    HttpMethod = HttpMethod.GET,
                    Id = new Guid("8c3f4176-04d0-5dc9-a570-99b8812a7176"),
                    ContentType = "application/json",
                    Description = "Find pet by ID",
                    HttpVersion = Hummingbird.TestFramework.Services.HttpVersion.Version11,
                    OperationName = "getPetById",
                    RequestType = typeof(Hummingbird.PetStore.Pet_Store.Pet_Store.getPetById),
                    UriTemplate = "https://petstore.swagger.io/v2",
                    Path = "/pet/{petId}",
                    ApplicationName = "Pet Store",
                    BodySerializer = Hummingbird.TestFramework.Serialization.AbstractSerializer.GetInstance(typeof(Hummingbird.TestFramework.Serialization.JsonSerializer)),
                    ServiceCategory = "Pet Store",
                    ServiceName = "pet",
                    ResponseType = typeof(Hummingbird.PetStore.Pet_Store.Pet_Store.getPetById_200),

                },

                new HttpRequestMetadata(){
                    HttpMethod = HttpMethod.POST,
                    Id = new Guid("e1220cb7-37b4-2760-7865-b2bfaa410ccd"),
                    ContentType = "application/x-www-form-urlencoded",
                    Description = "Updates a pet in the store with form data",
                    HttpVersion = Hummingbird.TestFramework.Services.HttpVersion.Version11,
                    OperationName = "updatePetWithForm",
                    RequestType = typeof(Hummingbird.PetStore.Pet_Store.Pet_Store.updatePetWithForm),
                    UriTemplate = "https://petstore.swagger.io/v2",
                    Path = "/pet/{petId}",
                    ApplicationName = "Pet Store",
                    BodySerializer = Hummingbird.TestFramework.Serialization.AbstractSerializer.GetInstance(typeof(Hummingbird.TestFramework.Serialization.FormUrlEncodedSerializer)),
                    ServiceCategory = "Pet Store",
                    ServiceName = "pet",
                    
                },

                new HttpRequestMetadata(){
                    HttpMethod = HttpMethod.DELETE,
                    Id = new Guid("90e60243-8f1c-1259-8cee-2b41f238c1b1"),
                    ContentType = "application/json",
                    Description = "Deletes a pet",
                    HttpVersion = Hummingbird.TestFramework.Services.HttpVersion.Version11,
                    OperationName = "deletePet",
                    RequestType = typeof(Hummingbird.PetStore.Pet_Store.Pet_Store.deletePet),
                    UriTemplate = "https://petstore.swagger.io/v2",
                    Path = "/pet/{petId}",
                    ApplicationName = "Pet Store",
                    BodySerializer = Hummingbird.TestFramework.Serialization.AbstractSerializer.GetInstance(typeof(Hummingbird.TestFramework.Serialization.JsonSerializer)),
                    ServiceCategory = "Pet Store",
                    ServiceName = "pet",
                    
                },

                new HttpRequestMetadata(){
                    HttpMethod = HttpMethod.POST,
                    Id = new Guid("95f72e20-d780-ae6b-9a14-b1f47f997570"),
                    ContentType = "application/json",
                    Description = "uploads an image",
                    HttpVersion = Hummingbird.TestFramework.Services.HttpVersion.Version11,
                    OperationName = "uploadFile",
                    RequestType = typeof(Hummingbird.PetStore.Pet_Store.Pet_Store.uploadFile),
                    UriTemplate = "https://petstore.swagger.io/v2",
                    Path = "/pet/{petId}/uploadImage",
                    ApplicationName = "Pet Store",
                    BodySerializer = Hummingbird.TestFramework.Serialization.AbstractSerializer.GetInstance(typeof(Hummingbird.TestFramework.Serialization.JsonSerializer)),
                    ServiceCategory = "Pet Store",
                    ServiceName = "pet",
                    ResponseType = typeof(Hummingbird.PetStore.Pet_Store.Pet_Store.uploadFile_200),

                },

                new HttpRequestMetadata(){
                    HttpMethod = HttpMethod.GET,
                    Id = new Guid("255412a2-1187-a210-7e52-a94bc78524c5"),
                    ContentType = "application/json",
                    Description = "Returns pet inventories by status",
                    HttpVersion = Hummingbird.TestFramework.Services.HttpVersion.Version11,
                    OperationName = "getInventory",
                    RequestType = typeof(Hummingbird.PetStore.Pet_Store.Pet_Store.getInventory),
                    UriTemplate = "https://petstore.swagger.io/v2",
                    Path = "/store/inventory",
                    ApplicationName = "Pet Store",
                    BodySerializer = Hummingbird.TestFramework.Serialization.AbstractSerializer.GetInstance(typeof(Hummingbird.TestFramework.Serialization.JsonSerializer)),
                    ServiceCategory = "Pet Store",
                    ServiceName = "store",
                    ResponseType = typeof(Hummingbird.PetStore.Pet_Store.Pet_Store.getInventory_200),

                },

                new HttpRequestMetadata(){
                    HttpMethod = HttpMethod.POST,
                    Id = new Guid("87f0b60c-6c0f-bba7-e7c0-2330de66dec6"),
                    ContentType = "application/json",
                    Description = "Place an order for a pet",
                    HttpVersion = Hummingbird.TestFramework.Services.HttpVersion.Version11,
                    OperationName = "placeOrder",
                    RequestType = typeof(Hummingbird.PetStore.Pet_Store.Pet_Store.placeOrder),
                    UriTemplate = "https://petstore.swagger.io/v2",
                    Path = "/store/order",
                    ApplicationName = "Pet Store",
                    BodySerializer = Hummingbird.TestFramework.Serialization.AbstractSerializer.GetInstance(typeof(Hummingbird.TestFramework.Serialization.JsonSerializer)),
                    ServiceCategory = "Pet Store",
                    ServiceName = "store",
                    ResponseType = typeof(Hummingbird.PetStore.Pet_Store.Pet_Store.placeOrder_200),

                },

                new HttpRequestMetadata(){
                    HttpMethod = HttpMethod.GET,
                    Id = new Guid("e8bd210d-138d-8d76-a194-b3013935cc64"),
                    ContentType = "application/json",
                    Description = "Find purchase order by ID",
                    HttpVersion = Hummingbird.TestFramework.Services.HttpVersion.Version11,
                    OperationName = "getOrderById",
                    RequestType = typeof(Hummingbird.PetStore.Pet_Store.Pet_Store.getOrderById),
                    UriTemplate = "https://petstore.swagger.io/v2",
                    Path = "/store/order/{orderId}",
                    ApplicationName = "Pet Store",
                    BodySerializer = Hummingbird.TestFramework.Serialization.AbstractSerializer.GetInstance(typeof(Hummingbird.TestFramework.Serialization.JsonSerializer)),
                    ServiceCategory = "Pet Store",
                    ServiceName = "store",
                    ResponseType = typeof(Hummingbird.PetStore.Pet_Store.Pet_Store.getOrderById_200),

                },

                new HttpRequestMetadata(){
                    HttpMethod = HttpMethod.DELETE,
                    Id = new Guid("c39f5b2d-b822-851d-d1a1-d6257820781c"),
                    ContentType = "application/json",
                    Description = "Delete purchase order by ID",
                    HttpVersion = Hummingbird.TestFramework.Services.HttpVersion.Version11,
                    OperationName = "deleteOrder",
                    RequestType = typeof(Hummingbird.PetStore.Pet_Store.Pet_Store.deleteOrder),
                    UriTemplate = "https://petstore.swagger.io/v2",
                    Path = "/store/order/{orderId}",
                    ApplicationName = "Pet Store",
                    BodySerializer = Hummingbird.TestFramework.Serialization.AbstractSerializer.GetInstance(typeof(Hummingbird.TestFramework.Serialization.JsonSerializer)),
                    ServiceCategory = "Pet Store",
                    ServiceName = "store",
                    
                },

                new HttpRequestMetadata(){
                    HttpMethod = HttpMethod.POST,
                    Id = new Guid("01b597b9-9517-e624-bee4-c2a5569eb248"),
                    ContentType = "application/json",
                    Description = "Create user",
                    HttpVersion = Hummingbird.TestFramework.Services.HttpVersion.Version11,
                    OperationName = "createUser",
                    RequestType = typeof(Hummingbird.PetStore.Pet_Store.Pet_Store.createUser),
                    UriTemplate = "https://petstore.swagger.io/v2",
                    Path = "/user",
                    ApplicationName = "Pet Store",
                    BodySerializer = Hummingbird.TestFramework.Serialization.AbstractSerializer.GetInstance(typeof(Hummingbird.TestFramework.Serialization.JsonSerializer)),
                    ServiceCategory = "Pet Store",
                    ServiceName = "user",
                    
                },

                new HttpRequestMetadata(){
                    HttpMethod = HttpMethod.POST,
                    Id = new Guid("daaf4ffa-453b-94c3-a414-3d2fc81495b2"),
                    ContentType = "application/json",
                    Description = "Creates list of users with given input array",
                    HttpVersion = Hummingbird.TestFramework.Services.HttpVersion.Version11,
                    OperationName = "createUsersWithArrayInput",
                    RequestType = typeof(Hummingbird.PetStore.Pet_Store.Pet_Store.createUsersWithArrayInput),
                    UriTemplate = "https://petstore.swagger.io/v2",
                    Path = "/user/createWithArray",
                    ApplicationName = "Pet Store",
                    BodySerializer = Hummingbird.TestFramework.Serialization.AbstractSerializer.GetInstance(typeof(Hummingbird.TestFramework.Serialization.JsonSerializer)),
                    ServiceCategory = "Pet Store",
                    ServiceName = "user",
                    
                },

                new HttpRequestMetadata(){
                    HttpMethod = HttpMethod.POST,
                    Id = new Guid("6ee5cb3f-1fb5-0b0d-5eb1-c3e902a2393a"),
                    ContentType = "application/json",
                    Description = "Creates list of users with given input array",
                    HttpVersion = Hummingbird.TestFramework.Services.HttpVersion.Version11,
                    OperationName = "createUsersWithListInput",
                    RequestType = typeof(Hummingbird.PetStore.Pet_Store.Pet_Store.createUsersWithListInput),
                    UriTemplate = "https://petstore.swagger.io/v2",
                    Path = "/user/createWithList",
                    ApplicationName = "Pet Store",
                    BodySerializer = Hummingbird.TestFramework.Serialization.AbstractSerializer.GetInstance(typeof(Hummingbird.TestFramework.Serialization.JsonSerializer)),
                    ServiceCategory = "Pet Store",
                    ServiceName = "user",
                    
                },

                new HttpRequestMetadata(){
                    HttpMethod = HttpMethod.GET,
                    Id = new Guid("bd9ff913-21f7-55cf-82ec-8cc983b6e0d8"),
                    ContentType = "application/json",
                    Description = "Logs user into the system",
                    HttpVersion = Hummingbird.TestFramework.Services.HttpVersion.Version11,
                    OperationName = "loginUser",
                    RequestType = typeof(Hummingbird.PetStore.Pet_Store.Pet_Store.loginUser),
                    UriTemplate = "https://petstore.swagger.io/v2",
                    Path = "/user/login",
                    ApplicationName = "Pet Store",
                    BodySerializer = Hummingbird.TestFramework.Serialization.AbstractSerializer.GetInstance(typeof(Hummingbird.TestFramework.Serialization.JsonSerializer)),
                    ServiceCategory = "Pet Store",
                    ServiceName = "user",
                    ResponseType = typeof(Hummingbird.PetStore.Pet_Store.Pet_Store.loginUser_200),

                },

                new HttpRequestMetadata(){
                    HttpMethod = HttpMethod.GET,
                    Id = new Guid("296d324c-ce2e-ac25-f503-2851ab01b6e3"),
                    ContentType = "application/json",
                    Description = "Logs out current logged in user session",
                    HttpVersion = Hummingbird.TestFramework.Services.HttpVersion.Version11,
                    OperationName = "logoutUser",
                    RequestType = typeof(Hummingbird.PetStore.Pet_Store.Pet_Store.logoutUser),
                    UriTemplate = "https://petstore.swagger.io/v2",
                    Path = "/user/logout",
                    ApplicationName = "Pet Store",
                    BodySerializer = Hummingbird.TestFramework.Serialization.AbstractSerializer.GetInstance(typeof(Hummingbird.TestFramework.Serialization.JsonSerializer)),
                    ServiceCategory = "Pet Store",
                    ServiceName = "user",
                    
                },

                new HttpRequestMetadata(){
                    HttpMethod = HttpMethod.GET,
                    Id = new Guid("9a4be190-6997-88d1-b9a3-1d963391d0d5"),
                    ContentType = "application/json",
                    Description = "Get user by user name",
                    HttpVersion = Hummingbird.TestFramework.Services.HttpVersion.Version11,
                    OperationName = "getUserByName",
                    RequestType = typeof(Hummingbird.PetStore.Pet_Store.Pet_Store.getUserByName),
                    UriTemplate = "https://petstore.swagger.io/v2",
                    Path = "/user/{username}",
                    ApplicationName = "Pet Store",
                    BodySerializer = Hummingbird.TestFramework.Serialization.AbstractSerializer.GetInstance(typeof(Hummingbird.TestFramework.Serialization.JsonSerializer)),
                    ServiceCategory = "Pet Store",
                    ServiceName = "user",
                    ResponseType = typeof(Hummingbird.PetStore.Pet_Store.Pet_Store.getUserByName_200),

                },

                new HttpRequestMetadata(){
                    HttpMethod = HttpMethod.PUT,
                    Id = new Guid("d9f78866-508e-64fc-7126-312935f439d0"),
                    ContentType = "application/json",
                    Description = "Updated user",
                    HttpVersion = Hummingbird.TestFramework.Services.HttpVersion.Version11,
                    OperationName = "updateUser",
                    RequestType = typeof(Hummingbird.PetStore.Pet_Store.Pet_Store.updateUser),
                    UriTemplate = "https://petstore.swagger.io/v2",
                    Path = "/user/{username}",
                    ApplicationName = "Pet Store",
                    BodySerializer = Hummingbird.TestFramework.Serialization.AbstractSerializer.GetInstance(typeof(Hummingbird.TestFramework.Serialization.JsonSerializer)),
                    ServiceCategory = "Pet Store",
                    ServiceName = "user",
                    
                },

                new HttpRequestMetadata(){
                    HttpMethod = HttpMethod.DELETE,
                    Id = new Guid("588e351c-ed77-bfb5-7242-75f94ca41809"),
                    ContentType = "application/json",
                    Description = "Delete user",
                    HttpVersion = Hummingbird.TestFramework.Services.HttpVersion.Version11,
                    OperationName = "deleteUser",
                    RequestType = typeof(Hummingbird.PetStore.Pet_Store.Pet_Store.deleteUser),
                    UriTemplate = "https://petstore.swagger.io/v2",
                    Path = "/user/{username}",
                    ApplicationName = "Pet Store",
                    BodySerializer = Hummingbird.TestFramework.Serialization.AbstractSerializer.GetInstance(typeof(Hummingbird.TestFramework.Serialization.JsonSerializer)),
                    ServiceCategory = "Pet Store",
                    ServiceName = "user",
                    
                },
				};
			}
		}

		public override HttpResponseMetadata[] HttpResponseServices
		{
			get
			{
	
				return new HttpResponseMetadata[]{

                new HttpResponseMetadata(){
                    HttpMethod = HttpMethod.POST,
                    ApplicationName = "Pet Store",
                    ServiceCategory = "Pet Store",
                    ServiceName = "pet",
                    OperationName = "addPet",
                    BodySerializer = Hummingbird.TestFramework.Serialization.AbstractSerializer.GetInstance(typeof(Hummingbird.TestFramework.Serialization.JsonSerializer)),
                    UriTemplate = "/pet",
                    ContentType = "application/json",
                    Id = new Guid("649d490b-75e3-0ac0-79e5-f250fbc331c5"),
                    Description = "Add a new pet to the store",
                    HttpVersion = Hummingbird.TestFramework.Services.HttpVersion.Version11,
                    RequestType = typeof(Hummingbird.PetStore.Pet_Store.Pet_Store.addPet),
                    
                },

                new HttpResponseMetadata(){
                    HttpMethod = HttpMethod.PUT,
                    ApplicationName = "Pet Store",
                    ServiceCategory = "Pet Store",
                    ServiceName = "pet",
                    OperationName = "updatePet",
                    BodySerializer = Hummingbird.TestFramework.Serialization.AbstractSerializer.GetInstance(typeof(Hummingbird.TestFramework.Serialization.JsonSerializer)),
                    UriTemplate = "/pet",
                    ContentType = "application/json",
                    Id = new Guid("0bdecb69-89a9-28c1-6cb4-6dcb2fea00c3"),
                    Description = "Update an existing pet",
                    HttpVersion = Hummingbird.TestFramework.Services.HttpVersion.Version11,
                    RequestType = typeof(Hummingbird.PetStore.Pet_Store.Pet_Store.updatePet),
                    
                },

                new HttpResponseMetadata(){
                    HttpMethod = HttpMethod.GET,
                    ApplicationName = "Pet Store",
                    ServiceCategory = "Pet Store",
                    ServiceName = "pet",
                    OperationName = "findPetsByStatus",
                    BodySerializer = Hummingbird.TestFramework.Serialization.AbstractSerializer.GetInstance(typeof(Hummingbird.TestFramework.Serialization.JsonSerializer)),
                    UriTemplate = "/pet/findByStatus",
                    ContentType = "application/json",
                    Id = new Guid("8ffa5088-b97f-2783-3c0d-f31fac6dd408"),
                    Description = "Finds Pets by status",
                    HttpVersion = Hummingbird.TestFramework.Services.HttpVersion.Version11,
                    RequestType = typeof(Hummingbird.PetStore.Pet_Store.Pet_Store.findPetsByStatus),
                    ResponseType = typeof(Hummingbird.PetStore.Pet_Store.Pet_Store.findPetsByStatus_200),

                },

                new HttpResponseMetadata(){
                    HttpMethod = HttpMethod.GET,
                    ApplicationName = "Pet Store",
                    ServiceCategory = "Pet Store",
                    ServiceName = "pet",
                    OperationName = "findPetsByTags",
                    BodySerializer = Hummingbird.TestFramework.Serialization.AbstractSerializer.GetInstance(typeof(Hummingbird.TestFramework.Serialization.JsonSerializer)),
                    UriTemplate = "/pet/findByTags",
                    ContentType = "application/json",
                    Id = new Guid("9392c251-b34c-c911-9b8a-bbe61ac238b3"),
                    Description = "Finds Pets by tags",
                    HttpVersion = Hummingbird.TestFramework.Services.HttpVersion.Version11,
                    RequestType = typeof(Hummingbird.PetStore.Pet_Store.Pet_Store.findPetsByTags),
                    ResponseType = typeof(Hummingbird.PetStore.Pet_Store.Pet_Store.findPetsByTags_200),

                },

                new HttpResponseMetadata(){
                    HttpMethod = HttpMethod.GET,
                    ApplicationName = "Pet Store",
                    ServiceCategory = "Pet Store",
                    ServiceName = "pet",
                    OperationName = "getPetById",
                    BodySerializer = Hummingbird.TestFramework.Serialization.AbstractSerializer.GetInstance(typeof(Hummingbird.TestFramework.Serialization.JsonSerializer)),
                    UriTemplate = "/pet/{petId}",
                    ContentType = "application/json",
                    Id = new Guid("bc42ecbd-7b6c-914d-9643-ce2c65082096"),
                    Description = "Find pet by ID",
                    HttpVersion = Hummingbird.TestFramework.Services.HttpVersion.Version11,
                    RequestType = typeof(Hummingbird.PetStore.Pet_Store.Pet_Store.getPetById),
                    ResponseType = typeof(Hummingbird.PetStore.Pet_Store.Pet_Store.getPetById_200),

                },

                new HttpResponseMetadata(){
                    HttpMethod = HttpMethod.POST,
                    ApplicationName = "Pet Store",
                    ServiceCategory = "Pet Store",
                    ServiceName = "pet",
                    OperationName = "updatePetWithForm",
                    BodySerializer = Hummingbird.TestFramework.Serialization.AbstractSerializer.GetInstance(typeof(Hummingbird.TestFramework.Serialization.FormUrlEncodedSerializer)),
                    UriTemplate = "/pet/{petId}",
                    ContentType = "application/x-www-form-urlencoded",
                    Id = new Guid("035c2ddb-a99f-92c4-b709-4c98add12d4c"),
                    Description = "Updates a pet in the store with form data",
                    HttpVersion = Hummingbird.TestFramework.Services.HttpVersion.Version11,
                    RequestType = typeof(Hummingbird.PetStore.Pet_Store.Pet_Store.updatePetWithForm),
                    
                },

                new HttpResponseMetadata(){
                    HttpMethod = HttpMethod.DELETE,
                    ApplicationName = "Pet Store",
                    ServiceCategory = "Pet Store",
                    ServiceName = "pet",
                    OperationName = "deletePet",
                    BodySerializer = Hummingbird.TestFramework.Serialization.AbstractSerializer.GetInstance(typeof(Hummingbird.TestFramework.Serialization.JsonSerializer)),
                    UriTemplate = "/pet/{petId}",
                    ContentType = "application/json",
                    Id = new Guid("af152b8b-354e-cc81-7e41-d7ae2611f0c7"),
                    Description = "Deletes a pet",
                    HttpVersion = Hummingbird.TestFramework.Services.HttpVersion.Version11,
                    RequestType = typeof(Hummingbird.PetStore.Pet_Store.Pet_Store.deletePet),
                    
                },

                new HttpResponseMetadata(){
                    HttpMethod = HttpMethod.POST,
                    ApplicationName = "Pet Store",
                    ServiceCategory = "Pet Store",
                    ServiceName = "pet",
                    OperationName = "uploadFile",
                    BodySerializer = Hummingbird.TestFramework.Serialization.AbstractSerializer.GetInstance(typeof(Hummingbird.TestFramework.Serialization.JsonSerializer)),
                    UriTemplate = "/pet/{petId}/uploadImage",
                    ContentType = "application/json",
                    Id = new Guid("99ca59d1-714a-64f3-33e3-6f398b9be06c"),
                    Description = "uploads an image",
                    HttpVersion = Hummingbird.TestFramework.Services.HttpVersion.Version11,
                    RequestType = typeof(Hummingbird.PetStore.Pet_Store.Pet_Store.uploadFile),
                    ResponseType = typeof(Hummingbird.PetStore.Pet_Store.Pet_Store.uploadFile_200),

                },

                new HttpResponseMetadata(){
                    HttpMethod = HttpMethod.GET,
                    ApplicationName = "Pet Store",
                    ServiceCategory = "Pet Store",
                    ServiceName = "store",
                    OperationName = "getInventory",
                    BodySerializer = Hummingbird.TestFramework.Serialization.AbstractSerializer.GetInstance(typeof(Hummingbird.TestFramework.Serialization.JsonSerializer)),
                    UriTemplate = "/store/inventory",
                    ContentType = "application/json",
                    Id = new Guid("98574a8d-54d3-959f-635b-a6ada397ce61"),
                    Description = "Returns pet inventories by status",
                    HttpVersion = Hummingbird.TestFramework.Services.HttpVersion.Version11,
                    RequestType = typeof(Hummingbird.PetStore.Pet_Store.Pet_Store.getInventory),
                    ResponseType = typeof(Hummingbird.PetStore.Pet_Store.Pet_Store.getInventory_200),

                },

                new HttpResponseMetadata(){
                    HttpMethod = HttpMethod.POST,
                    ApplicationName = "Pet Store",
                    ServiceCategory = "Pet Store",
                    ServiceName = "store",
                    OperationName = "placeOrder",
                    BodySerializer = Hummingbird.TestFramework.Serialization.AbstractSerializer.GetInstance(typeof(Hummingbird.TestFramework.Serialization.JsonSerializer)),
                    UriTemplate = "/store/order",
                    ContentType = "application/json",
                    Id = new Guid("babea399-76d2-df08-9c69-73b4674ce06f"),
                    Description = "Place an order for a pet",
                    HttpVersion = Hummingbird.TestFramework.Services.HttpVersion.Version11,
                    RequestType = typeof(Hummingbird.PetStore.Pet_Store.Pet_Store.placeOrder),
                    ResponseType = typeof(Hummingbird.PetStore.Pet_Store.Pet_Store.placeOrder_200),

                },

                new HttpResponseMetadata(){
                    HttpMethod = HttpMethod.GET,
                    ApplicationName = "Pet Store",
                    ServiceCategory = "Pet Store",
                    ServiceName = "store",
                    OperationName = "getOrderById",
                    BodySerializer = Hummingbird.TestFramework.Serialization.AbstractSerializer.GetInstance(typeof(Hummingbird.TestFramework.Serialization.JsonSerializer)),
                    UriTemplate = "/store/order/{orderId}",
                    ContentType = "application/json",
                    Id = new Guid("861b9581-3671-70d5-9d54-c04183451135"),
                    Description = "Find purchase order by ID",
                    HttpVersion = Hummingbird.TestFramework.Services.HttpVersion.Version11,
                    RequestType = typeof(Hummingbird.PetStore.Pet_Store.Pet_Store.getOrderById),
                    ResponseType = typeof(Hummingbird.PetStore.Pet_Store.Pet_Store.getOrderById_200),

                },

                new HttpResponseMetadata(){
                    HttpMethod = HttpMethod.DELETE,
                    ApplicationName = "Pet Store",
                    ServiceCategory = "Pet Store",
                    ServiceName = "store",
                    OperationName = "deleteOrder",
                    BodySerializer = Hummingbird.TestFramework.Serialization.AbstractSerializer.GetInstance(typeof(Hummingbird.TestFramework.Serialization.JsonSerializer)),
                    UriTemplate = "/store/order/{orderId}",
                    ContentType = "application/json",
                    Id = new Guid("18289506-65e4-0c77-98f2-5dc114e0b83b"),
                    Description = "Delete purchase order by ID",
                    HttpVersion = Hummingbird.TestFramework.Services.HttpVersion.Version11,
                    RequestType = typeof(Hummingbird.PetStore.Pet_Store.Pet_Store.deleteOrder),
                    
                },

                new HttpResponseMetadata(){
                    HttpMethod = HttpMethod.POST,
                    ApplicationName = "Pet Store",
                    ServiceCategory = "Pet Store",
                    ServiceName = "user",
                    OperationName = "createUser",
                    BodySerializer = Hummingbird.TestFramework.Serialization.AbstractSerializer.GetInstance(typeof(Hummingbird.TestFramework.Serialization.JsonSerializer)),
                    UriTemplate = "/user",
                    ContentType = "application/json",
                    Id = new Guid("78219939-0e7e-6ca5-ab9e-70e6fd50c10c"),
                    Description = "Create user",
                    HttpVersion = Hummingbird.TestFramework.Services.HttpVersion.Version11,
                    RequestType = typeof(Hummingbird.PetStore.Pet_Store.Pet_Store.createUser),
                    
                },

                new HttpResponseMetadata(){
                    HttpMethod = HttpMethod.POST,
                    ApplicationName = "Pet Store",
                    ServiceCategory = "Pet Store",
                    ServiceName = "user",
                    OperationName = "createUsersWithArrayInput",
                    BodySerializer = Hummingbird.TestFramework.Serialization.AbstractSerializer.GetInstance(typeof(Hummingbird.TestFramework.Serialization.JsonSerializer)),
                    UriTemplate = "/user/createWithArray",
                    ContentType = "application/json",
                    Id = new Guid("41a48bc3-087d-d268-c1f7-bf1a809e76c4"),
                    Description = "Creates list of users with given input array",
                    HttpVersion = Hummingbird.TestFramework.Services.HttpVersion.Version11,
                    RequestType = typeof(Hummingbird.PetStore.Pet_Store.Pet_Store.createUsersWithArrayInput),
                    
                },

                new HttpResponseMetadata(){
                    HttpMethod = HttpMethod.POST,
                    ApplicationName = "Pet Store",
                    ServiceCategory = "Pet Store",
                    ServiceName = "user",
                    OperationName = "createUsersWithListInput",
                    BodySerializer = Hummingbird.TestFramework.Serialization.AbstractSerializer.GetInstance(typeof(Hummingbird.TestFramework.Serialization.JsonSerializer)),
                    UriTemplate = "/user/createWithList",
                    ContentType = "application/json",
                    Id = new Guid("040749c9-2375-fb27-02eb-2f5da0402a86"),
                    Description = "Creates list of users with given input array",
                    HttpVersion = Hummingbird.TestFramework.Services.HttpVersion.Version11,
                    RequestType = typeof(Hummingbird.PetStore.Pet_Store.Pet_Store.createUsersWithListInput),
                    
                },

                new HttpResponseMetadata(){
                    HttpMethod = HttpMethod.GET,
                    ApplicationName = "Pet Store",
                    ServiceCategory = "Pet Store",
                    ServiceName = "user",
                    OperationName = "loginUser",
                    BodySerializer = Hummingbird.TestFramework.Serialization.AbstractSerializer.GetInstance(typeof(Hummingbird.TestFramework.Serialization.JsonSerializer)),
                    UriTemplate = "/user/login",
                    ContentType = "application/json",
                    Id = new Guid("1237c6c3-1a9f-c742-6e7d-c60949d7adf4"),
                    Description = "Logs user into the system",
                    HttpVersion = Hummingbird.TestFramework.Services.HttpVersion.Version11,
                    RequestType = typeof(Hummingbird.PetStore.Pet_Store.Pet_Store.loginUser),
                    ResponseType = typeof(Hummingbird.PetStore.Pet_Store.Pet_Store.loginUser_200),

                },

                new HttpResponseMetadata(){
                    HttpMethod = HttpMethod.GET,
                    ApplicationName = "Pet Store",
                    ServiceCategory = "Pet Store",
                    ServiceName = "user",
                    OperationName = "logoutUser",
                    BodySerializer = Hummingbird.TestFramework.Serialization.AbstractSerializer.GetInstance(typeof(Hummingbird.TestFramework.Serialization.JsonSerializer)),
                    UriTemplate = "/user/logout",
                    ContentType = "application/json",
                    Id = new Guid("fe58b5d8-71ee-d05b-1b2b-0b7384a5dfb6"),
                    Description = "Logs out current logged in user session",
                    HttpVersion = Hummingbird.TestFramework.Services.HttpVersion.Version11,
                    RequestType = typeof(Hummingbird.PetStore.Pet_Store.Pet_Store.logoutUser),
                    
                },

                new HttpResponseMetadata(){
                    HttpMethod = HttpMethod.GET,
                    ApplicationName = "Pet Store",
                    ServiceCategory = "Pet Store",
                    ServiceName = "user",
                    OperationName = "getUserByName",
                    BodySerializer = Hummingbird.TestFramework.Serialization.AbstractSerializer.GetInstance(typeof(Hummingbird.TestFramework.Serialization.JsonSerializer)),
                    UriTemplate = "/user/{username}",
                    ContentType = "application/json",
                    Id = new Guid("936d49fc-97f7-9ce5-a670-fd4842d9889a"),
                    Description = "Get user by user name",
                    HttpVersion = Hummingbird.TestFramework.Services.HttpVersion.Version11,
                    RequestType = typeof(Hummingbird.PetStore.Pet_Store.Pet_Store.getUserByName),
                    ResponseType = typeof(Hummingbird.PetStore.Pet_Store.Pet_Store.getUserByName_200),

                },

                new HttpResponseMetadata(){
                    HttpMethod = HttpMethod.PUT,
                    ApplicationName = "Pet Store",
                    ServiceCategory = "Pet Store",
                    ServiceName = "user",
                    OperationName = "updateUser",
                    BodySerializer = Hummingbird.TestFramework.Serialization.AbstractSerializer.GetInstance(typeof(Hummingbird.TestFramework.Serialization.JsonSerializer)),
                    UriTemplate = "/user/{username}",
                    ContentType = "application/json",
                    Id = new Guid("68c00ffe-1a31-1bcf-f53a-3e796335034d"),
                    Description = "Updated user",
                    HttpVersion = Hummingbird.TestFramework.Services.HttpVersion.Version11,
                    RequestType = typeof(Hummingbird.PetStore.Pet_Store.Pet_Store.updateUser),
                    
                },

                new HttpResponseMetadata(){
                    HttpMethod = HttpMethod.DELETE,
                    ApplicationName = "Pet Store",
                    ServiceCategory = "Pet Store",
                    ServiceName = "user",
                    OperationName = "deleteUser",
                    BodySerializer = Hummingbird.TestFramework.Serialization.AbstractSerializer.GetInstance(typeof(Hummingbird.TestFramework.Serialization.JsonSerializer)),
                    UriTemplate = "/user/{username}",
                    ContentType = "application/json",
                    Id = new Guid("45a9293a-a8d4-57d5-297b-365d8071f665"),
                    Description = "Delete user",
                    HttpVersion = Hummingbird.TestFramework.Services.HttpVersion.Version11,
                    RequestType = typeof(Hummingbird.PetStore.Pet_Store.Pet_Store.deleteUser),
                    
                },
				};
			}
		}
			
        public override Parameter[] ServerParameters
        {
            get
            {
                return new Parameter[0];
            }
        }

        public override Parameter[] ClientParameters
        {
            get
            {
                return new Parameter[0];
            }
        }

	}
}
