// This class is generated by Hummingbird Test Framework
// Hummingbird.TestFramework, A product of Hummingbird ALM tool set
// Hummingbird.TestManager, A product of Hummingbird ALM tool set
// Copyright (c) 2014-2018 Huaxing YUAN, All rights reserved
// Template created at: 2018-09-28 00:38 by Huaxing YUAN
using Hummingbird.TestFramework.Extensibility;
using Hummingbird.TestFramework.ExtensionProject;
using Hummingbird.TestFramework.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.ServiceModel;
using System.ServiceModel.Channels;
using System.Text;
using System.Threading.Tasks;

namespace Hummingbird.PetStore
{
	public class MyHttpServiceExtension : HttpServiceExtension
	{

		public override HttpRequestMetadata[] HttpRequestServices
		{
			get
			{
				return new HttpRequestMetadata[]
				{

            new HttpRequestMetadata(){
                HttpMethod = HttpMethod.POST,
                Id = new Guid("19139641-475f-380b-6e58-4a6e7001f451"),
                ContentType = "application/json",
                Description = "Add a new pet to the store",
                HttpVersion = Hummingbird.TestFramework.Services.HttpVersion.Version11,
                OperationName = "addPet",
                RequestType = typeof(Hummingbird.PetStore.Pet_Store.Pet_Store.addPet),
                UriTemplate = "https://petstore.swagger.io/v2",
                Path = "/pet",
                ApplicationName = "Pet Store",
                BodySerializer = Hummingbird.TestFramework.Serialization.AbstractSerializer.GetInstance(typeof(Hummingbird.TestFramework.Serialization.JsonSerializer)),
                ServiceCategory = "Pet Store",
                ServiceName = "pet",
            },

            new HttpRequestMetadata(){
                HttpMethod = HttpMethod.PUT,
                Id = new Guid("1a372ac9-62fa-5e9c-7e12-252781730ced"),
                ContentType = "application/json",
                Description = "Update an existing pet",
                HttpVersion = Hummingbird.TestFramework.Services.HttpVersion.Version11,
                OperationName = "updatePet",
                RequestType = typeof(Hummingbird.PetStore.Pet_Store.Pet_Store.updatePet),
                UriTemplate = "https://petstore.swagger.io/v2",
                Path = "/pet",
                ApplicationName = "Pet Store",
                BodySerializer = Hummingbird.TestFramework.Serialization.AbstractSerializer.GetInstance(typeof(Hummingbird.TestFramework.Serialization.JsonSerializer)),
                ServiceCategory = "Pet Store",
                ServiceName = "pet",
            },

            new HttpRequestMetadata(){
                HttpMethod = HttpMethod.GET,
                Id = new Guid("04aaec70-57ea-7bfe-554a-a3e7fc49abe6"),
                ContentType = "application/json",
                Description = "Finds Pets by status",
                HttpVersion = Hummingbird.TestFramework.Services.HttpVersion.Version11,
                OperationName = "findPetsByStatus",
                RequestType = typeof(Hummingbird.PetStore.Pet_Store.Pet_Store.findPetsByStatus),
                UriTemplate = "https://petstore.swagger.io/v2",
                Path = "/pet/findByStatus",
                ApplicationName = "Pet Store",
                BodySerializer = Hummingbird.TestFramework.Serialization.AbstractSerializer.GetInstance(typeof(Hummingbird.TestFramework.Serialization.JsonSerializer)),
                ServiceCategory = "Pet Store",
                ServiceName = "pet",
            },

            new HttpRequestMetadata(){
                HttpMethod = HttpMethod.GET,
                Id = new Guid("0330ee22-5109-4b69-fc88-735f8de2be9a"),
                ContentType = "application/json",
                Description = "Finds Pets by tags",
                HttpVersion = Hummingbird.TestFramework.Services.HttpVersion.Version11,
                OperationName = "findPetsByTags",
                RequestType = typeof(Hummingbird.PetStore.Pet_Store.Pet_Store.findPetsByTags),
                UriTemplate = "https://petstore.swagger.io/v2",
                Path = "/pet/findByTags",
                ApplicationName = "Pet Store",
                BodySerializer = Hummingbird.TestFramework.Serialization.AbstractSerializer.GetInstance(typeof(Hummingbird.TestFramework.Serialization.JsonSerializer)),
                ServiceCategory = "Pet Store",
                ServiceName = "pet",
            },

            new HttpRequestMetadata(){
                HttpMethod = HttpMethod.GET,
                Id = new Guid("8c3f4176-04d0-5dc9-a570-99b8812a7176"),
                ContentType = "application/json",
                Description = "Find pet by ID",
                HttpVersion = Hummingbird.TestFramework.Services.HttpVersion.Version11,
                OperationName = "getPetById",
                RequestType = typeof(Hummingbird.PetStore.Pet_Store.Pet_Store.getPetById),
                UriTemplate = "https://petstore.swagger.io/v2",
                Path = "/pet/{petId}",
                ApplicationName = "Pet Store",
                BodySerializer = Hummingbird.TestFramework.Serialization.AbstractSerializer.GetInstance(typeof(Hummingbird.TestFramework.Serialization.JsonSerializer)),
                ServiceCategory = "Pet Store",
                ServiceName = "pet",
            },

            new HttpRequestMetadata(){
                HttpMethod = HttpMethod.POST,
                Id = new Guid("e1220cb7-37b4-2760-7865-b2bfaa410ccd"),
                ContentType = "application/x-www-form-urlencoded",
                Description = "Updates a pet in the store with form data",
                HttpVersion = Hummingbird.TestFramework.Services.HttpVersion.Version11,
                OperationName = "updatePetWithForm",
                RequestType = typeof(Hummingbird.PetStore.Pet_Store.Pet_Store.updatePetWithForm),
                UriTemplate = "https://petstore.swagger.io/v2",
                Path = "/pet/{petId}",
                ApplicationName = "Pet Store",
                BodySerializer = Hummingbird.TestFramework.Serialization.AbstractSerializer.GetInstance(typeof(Hummingbird.TestFramework.Serialization.FormUrlEncodedSerializer)),
                ServiceCategory = "Pet Store",
                ServiceName = "pet",
            },

            new HttpRequestMetadata(){
                HttpMethod = HttpMethod.DELETE,
                Id = new Guid("90e60243-8f1c-1259-8cee-2b41f238c1b1"),
                ContentType = "application/json",
                Description = "Deletes a pet",
                HttpVersion = Hummingbird.TestFramework.Services.HttpVersion.Version11,
                OperationName = "deletePet",
                RequestType = typeof(Hummingbird.PetStore.Pet_Store.Pet_Store.deletePet),
                UriTemplate = "https://petstore.swagger.io/v2",
                Path = "/pet/{petId}",
                ApplicationName = "Pet Store",
                BodySerializer = Hummingbird.TestFramework.Serialization.AbstractSerializer.GetInstance(typeof(Hummingbird.TestFramework.Serialization.JsonSerializer)),
                ServiceCategory = "Pet Store",
                ServiceName = "pet",
            },

            new HttpRequestMetadata(){
                HttpMethod = HttpMethod.POST,
                Id = new Guid("95f72e20-d780-ae6b-9a14-b1f47f997570"),
                ContentType = "application/json",
                Description = "uploads an image",
                HttpVersion = Hummingbird.TestFramework.Services.HttpVersion.Version11,
                OperationName = "uploadFile",
                RequestType = typeof(Hummingbird.PetStore.Pet_Store.Pet_Store.uploadFile),
                UriTemplate = "https://petstore.swagger.io/v2",
                Path = "/pet/{petId}/uploadImage",
                ApplicationName = "Pet Store",
                BodySerializer = Hummingbird.TestFramework.Serialization.AbstractSerializer.GetInstance(typeof(Hummingbird.TestFramework.Serialization.JsonSerializer)),
                ServiceCategory = "Pet Store",
                ServiceName = "pet",
            },

            new HttpRequestMetadata(){
                HttpMethod = HttpMethod.GET,
                Id = new Guid("255412a2-1187-a210-7e52-a94bc78524c5"),
                ContentType = "application/json",
                Description = "Returns pet inventories by status",
                HttpVersion = Hummingbird.TestFramework.Services.HttpVersion.Version11,
                OperationName = "getInventory",
                RequestType = typeof(Hummingbird.PetStore.Pet_Store.Pet_Store.getInventory),
                UriTemplate = "https://petstore.swagger.io/v2",
                Path = "/store/inventory",
                ApplicationName = "Pet Store",
                BodySerializer = Hummingbird.TestFramework.Serialization.AbstractSerializer.GetInstance(typeof(Hummingbird.TestFramework.Serialization.JsonSerializer)),
                ServiceCategory = "Pet Store",
                ServiceName = "store",
            },

            new HttpRequestMetadata(){
                HttpMethod = HttpMethod.POST,
                Id = new Guid("87f0b60c-6c0f-bba7-e7c0-2330de66dec6"),
                ContentType = "application/json",
                Description = "Place an order for a pet",
                HttpVersion = Hummingbird.TestFramework.Services.HttpVersion.Version11,
                OperationName = "placeOrder",
                RequestType = typeof(Hummingbird.PetStore.Pet_Store.Pet_Store.placeOrder),
                UriTemplate = "https://petstore.swagger.io/v2",
                Path = "/store/order",
                ApplicationName = "Pet Store",
                BodySerializer = Hummingbird.TestFramework.Serialization.AbstractSerializer.GetInstance(typeof(Hummingbird.TestFramework.Serialization.JsonSerializer)),
                ServiceCategory = "Pet Store",
                ServiceName = "store",
            },

            new HttpRequestMetadata(){
                HttpMethod = HttpMethod.GET,
                Id = new Guid("e8bd210d-138d-8d76-a194-b3013935cc64"),
                ContentType = "application/json",
                Description = "Find purchase order by ID",
                HttpVersion = Hummingbird.TestFramework.Services.HttpVersion.Version11,
                OperationName = "getOrderById",
                RequestType = typeof(Hummingbird.PetStore.Pet_Store.Pet_Store.getOrderById),
                UriTemplate = "https://petstore.swagger.io/v2",
                Path = "/store/order/{orderId}",
                ApplicationName = "Pet Store",
                BodySerializer = Hummingbird.TestFramework.Serialization.AbstractSerializer.GetInstance(typeof(Hummingbird.TestFramework.Serialization.JsonSerializer)),
                ServiceCategory = "Pet Store",
                ServiceName = "store",
            },

            new HttpRequestMetadata(){
                HttpMethod = HttpMethod.DELETE,
                Id = new Guid("c39f5b2d-b822-851d-d1a1-d6257820781c"),
                ContentType = "application/json",
                Description = "Delete purchase order by ID",
                HttpVersion = Hummingbird.TestFramework.Services.HttpVersion.Version11,
                OperationName = "deleteOrder",
                RequestType = typeof(Hummingbird.PetStore.Pet_Store.Pet_Store.deleteOrder),
                UriTemplate = "https://petstore.swagger.io/v2",
                Path = "/store/order/{orderId}",
                ApplicationName = "Pet Store",
                BodySerializer = Hummingbird.TestFramework.Serialization.AbstractSerializer.GetInstance(typeof(Hummingbird.TestFramework.Serialization.JsonSerializer)),
                ServiceCategory = "Pet Store",
                ServiceName = "store",
            },

            new HttpRequestMetadata(){
                HttpMethod = HttpMethod.POST,
                Id = new Guid("01b597b9-9517-e624-bee4-c2a5569eb248"),
                ContentType = "application/json",
                Description = "Create user",
                HttpVersion = Hummingbird.TestFramework.Services.HttpVersion.Version11,
                OperationName = "createUser",
                RequestType = typeof(Hummingbird.PetStore.Pet_Store.Pet_Store.createUser),
                UriTemplate = "https://petstore.swagger.io/v2",
                Path = "/user",
                ApplicationName = "Pet Store",
                BodySerializer = Hummingbird.TestFramework.Serialization.AbstractSerializer.GetInstance(typeof(Hummingbird.TestFramework.Serialization.JsonSerializer)),
                ServiceCategory = "Pet Store",
                ServiceName = "user",
            },

            new HttpRequestMetadata(){
                HttpMethod = HttpMethod.POST,
                Id = new Guid("daaf4ffa-453b-94c3-a414-3d2fc81495b2"),
                ContentType = "application/json",
                Description = "Creates list of users with given input array",
                HttpVersion = Hummingbird.TestFramework.Services.HttpVersion.Version11,
                OperationName = "createUsersWithArrayInput",
                RequestType = typeof(Hummingbird.PetStore.Pet_Store.Pet_Store.createUsersWithArrayInput),
                UriTemplate = "https://petstore.swagger.io/v2",
                Path = "/user/createWithArray",
                ApplicationName = "Pet Store",
                BodySerializer = Hummingbird.TestFramework.Serialization.AbstractSerializer.GetInstance(typeof(Hummingbird.TestFramework.Serialization.JsonSerializer)),
                ServiceCategory = "Pet Store",
                ServiceName = "user",
            },

            new HttpRequestMetadata(){
                HttpMethod = HttpMethod.POST,
                Id = new Guid("6ee5cb3f-1fb5-0b0d-5eb1-c3e902a2393a"),
                ContentType = "application/json",
                Description = "Creates list of users with given input array",
                HttpVersion = Hummingbird.TestFramework.Services.HttpVersion.Version11,
                OperationName = "createUsersWithListInput",
                RequestType = typeof(Hummingbird.PetStore.Pet_Store.Pet_Store.createUsersWithListInput),
                UriTemplate = "https://petstore.swagger.io/v2",
                Path = "/user/createWithList",
                ApplicationName = "Pet Store",
                BodySerializer = Hummingbird.TestFramework.Serialization.AbstractSerializer.GetInstance(typeof(Hummingbird.TestFramework.Serialization.JsonSerializer)),
                ServiceCategory = "Pet Store",
                ServiceName = "user",
            },

            new HttpRequestMetadata(){
                HttpMethod = HttpMethod.GET,
                Id = new Guid("bd9ff913-21f7-55cf-82ec-8cc983b6e0d8"),
                ContentType = "application/json",
                Description = "Logs user into the system",
                HttpVersion = Hummingbird.TestFramework.Services.HttpVersion.Version11,
                OperationName = "loginUser",
                RequestType = typeof(Hummingbird.PetStore.Pet_Store.Pet_Store.loginUser),
                UriTemplate = "https://petstore.swagger.io/v2",
                Path = "/user/login",
                ApplicationName = "Pet Store",
                BodySerializer = Hummingbird.TestFramework.Serialization.AbstractSerializer.GetInstance(typeof(Hummingbird.TestFramework.Serialization.JsonSerializer)),
                ServiceCategory = "Pet Store",
                ServiceName = "user",
            },

            new HttpRequestMetadata(){
                HttpMethod = HttpMethod.GET,
                Id = new Guid("296d324c-ce2e-ac25-f503-2851ab01b6e3"),
                ContentType = "application/json",
                Description = "Logs out current logged in user session",
                HttpVersion = Hummingbird.TestFramework.Services.HttpVersion.Version11,
                OperationName = "logoutUser",
                RequestType = typeof(Hummingbird.PetStore.Pet_Store.Pet_Store.logoutUser),
                UriTemplate = "https://petstore.swagger.io/v2",
                Path = "/user/logout",
                ApplicationName = "Pet Store",
                BodySerializer = Hummingbird.TestFramework.Serialization.AbstractSerializer.GetInstance(typeof(Hummingbird.TestFramework.Serialization.JsonSerializer)),
                ServiceCategory = "Pet Store",
                ServiceName = "user",
            },

            new HttpRequestMetadata(){
                HttpMethod = HttpMethod.GET,
                Id = new Guid("9a4be190-6997-88d1-b9a3-1d963391d0d5"),
                ContentType = "application/json",
                Description = "Get user by user name",
                HttpVersion = Hummingbird.TestFramework.Services.HttpVersion.Version11,
                OperationName = "getUserByName",
                RequestType = typeof(Hummingbird.PetStore.Pet_Store.Pet_Store.getUserByName),
                UriTemplate = "https://petstore.swagger.io/v2",
                Path = "/user/{username}",
                ApplicationName = "Pet Store",
                BodySerializer = Hummingbird.TestFramework.Serialization.AbstractSerializer.GetInstance(typeof(Hummingbird.TestFramework.Serialization.JsonSerializer)),
                ServiceCategory = "Pet Store",
                ServiceName = "user",
            },

            new HttpRequestMetadata(){
                HttpMethod = HttpMethod.PUT,
                Id = new Guid("d9f78866-508e-64fc-7126-312935f439d0"),
                ContentType = "application/json",
                Description = "Updated user",
                HttpVersion = Hummingbird.TestFramework.Services.HttpVersion.Version11,
                OperationName = "updateUser",
                RequestType = typeof(Hummingbird.PetStore.Pet_Store.Pet_Store.updateUser),
                UriTemplate = "https://petstore.swagger.io/v2",
                Path = "/user/{username}",
                ApplicationName = "Pet Store",
                BodySerializer = Hummingbird.TestFramework.Serialization.AbstractSerializer.GetInstance(typeof(Hummingbird.TestFramework.Serialization.JsonSerializer)),
                ServiceCategory = "Pet Store",
                ServiceName = "user",
            },

            new HttpRequestMetadata(){
                HttpMethod = HttpMethod.DELETE,
                Id = new Guid("588e351c-ed77-bfb5-7242-75f94ca41809"),
                ContentType = "application/json",
                Description = "Delete user",
                HttpVersion = Hummingbird.TestFramework.Services.HttpVersion.Version11,
                OperationName = "deleteUser",
                RequestType = typeof(Hummingbird.PetStore.Pet_Store.Pet_Store.deleteUser),
                UriTemplate = "https://petstore.swagger.io/v2",
                Path = "/user/{username}",
                ApplicationName = "Pet Store",
                BodySerializer = Hummingbird.TestFramework.Serialization.AbstractSerializer.GetInstance(typeof(Hummingbird.TestFramework.Serialization.JsonSerializer)),
                ServiceCategory = "Pet Store",
                ServiceName = "user",
            },
				};
			}
		}

		public override HttpResponseMetadata[] HttpResponseServices
		{
			get
			{
	
				return new HttpResponseMetadata[]{

				};
			}
		}
			
        public override Parameter[] ServerParameters
        {
            get
            {
                return new Parameter[0];
            }
        }

        public override Parameter[] ClientParameters
        {
            get
            {
                return new Parameter[0];
            }
        }

	}
}
