// This class is generated by Hummingbird Test Framework
// Hummingbird.TestFramework, A product of Hummingbird ALM tool set
// Hummingbird.TestManager, A product of Hummingbird ALM tool set
// Copyright (c) 2014-2018 Huaxing YUAN, All rights reserved
// Template created at: 2018-09-28 00:38 by Huaxing YUAN
using Hummingbird.TestFramework.Extensibility;
using Hummingbird.TestFramework.ExtensionProject;
using Hummingbird.TestFramework.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.ServiceModel;
using System.ServiceModel.Channels;
using System.Text;
using System.Threading.Tasks;

namespace Hummingbird.OAuth2Extension
{
	public class MyHttpServiceExtension : HttpServiceExtension
	{

		public override HttpRequestMetadata[] HttpRequestServices
		{
			get
			{
				return new HttpRequestMetadata[]
				{

                new HttpRequestMetadata(){
                    HttpMethod = HttpMethod.GET,
                    Id = new Guid("f5e18534-b68a-349c-d723-a86b32ba8882"),
                    ContentType = "application/json",
                    Description = "Authentication Endpoint",
                    HttpVersion = Hummingbird.TestFramework.Services.HttpVersion.Version11,
                    OperationName = "auth",
                    RequestType = typeof(Hummingbird.OAuth2Extension.OAuth2_Grant.Authorization_Code.auth),
                    UriTemplate = "https://${OAuth2_Server}",
                    Path = "/auth",
                    ApplicationName = "OAuth2 Grant",
                    BodySerializer = Hummingbird.TestFramework.Serialization.AbstractSerializer.GetInstance(typeof(Hummingbird.TestFramework.Serialization.JsonSerializer)),
                    ServiceCategory = "Authorization Code",
                    ServiceName = "oauth2",
                    
                },

                new HttpRequestMetadata(){
                    HttpMethod = HttpMethod.POST,
                    Id = new Guid("aa41d7d9-9b7a-3583-f61e-e8e89b3d978b"),
                    ContentType = "application/x-www-form-urlencoded",
                    Description = "Request Access Token",
                    HttpVersion = Hummingbird.TestFramework.Services.HttpVersion.Version11,
                    OperationName = "getToken",
                    RequestType = typeof(Hummingbird.OAuth2Extension.OAuth2_Grant.Authorization_Code.getToken),
                    UriTemplate = "https://${OAuth2_Server}",
                    Path = "/token",
                    ApplicationName = "OAuth2 Grant",
                    BodySerializer = Hummingbird.TestFramework.Serialization.AbstractSerializer.GetInstance(typeof(Hummingbird.TestFramework.Serialization.FormUrlEncodedSerializer)),
                    ServiceCategory = "Authorization Code",
                    ServiceName = "oauth2",
                    
                },

                new HttpRequestMetadata(){
                    HttpMethod = HttpMethod.DELETE,
                    Id = new Guid("4552adbd-6cc0-cf25-2aa9-53263296ea06"),
                    ContentType = "application/json",
                    Description = "Invalidate access token",
                    HttpVersion = Hummingbird.TestFramework.Services.HttpVersion.Version11,
                    OperationName = "deleteToken",
                    RequestType = typeof(Hummingbird.OAuth2Extension.OAuth2_Grant.Authorization_Code.deleteToken),
                    UriTemplate = "https://${OAuth2_Server}",
                    Path = "/token",
                    ApplicationName = "OAuth2 Grant",
                    BodySerializer = Hummingbird.TestFramework.Serialization.AbstractSerializer.GetInstance(typeof(Hummingbird.TestFramework.Serialization.JsonSerializer)),
                    ServiceCategory = "Authorization Code",
                    ServiceName = "oauth2",
                    
                },

                new HttpRequestMetadata(){
                    HttpMethod = HttpMethod.POST,
                    Id = new Guid("8616552f-a301-144b-74a7-2bf7c0ac9ea1"),
                    ContentType = "application/x-www-form-urlencoded",
                    Description = "Request Access Token",
                    HttpVersion = Hummingbird.TestFramework.Services.HttpVersion.Version11,
                    OperationName = "Post_Request_Access_Token",
                    RequestType = typeof(Hummingbird.OAuth2Extension.OAuth2_Grant.Client_Credentials.Post_Request_Access_Token),
                    UriTemplate = "https://${OAuth2_Server}",
                    Path = "/token",
                    ApplicationName = "OAuth2 Grant",
                    BodySerializer = Hummingbird.TestFramework.Serialization.AbstractSerializer.GetInstance(typeof(Hummingbird.TestFramework.Serialization.FormUrlEncodedSerializer)),
                    ServiceCategory = "Client Credentials",
                    ServiceName = "Oauth2",
                    
                },

                new HttpRequestMetadata(){
                    HttpMethod = HttpMethod.DELETE,
                    Id = new Guid("c7bc00e7-83d6-d739-699e-0c09aaf0e308"),
                    ContentType = "application/json",
                    Description = "Invalidate access token",
                    HttpVersion = Hummingbird.TestFramework.Services.HttpVersion.Version11,
                    OperationName = "Delete_Invalidate_access_token",
                    RequestType = typeof(Hummingbird.OAuth2Extension.OAuth2_Grant.Client_Credentials.Delete_Invalidate_access_token),
                    UriTemplate = "https://${OAuth2_Server}",
                    Path = "/token",
                    ApplicationName = "OAuth2 Grant",
                    BodySerializer = Hummingbird.TestFramework.Serialization.AbstractSerializer.GetInstance(typeof(Hummingbird.TestFramework.Serialization.JsonSerializer)),
                    ServiceCategory = "Client Credentials",
                    ServiceName = "Oauth2",
                    
                },

                new HttpRequestMetadata(){
                    HttpMethod = HttpMethod.GET,
                    Id = new Guid("2cd692f3-fe32-b467-e419-13f07ed9de0a"),
                    ContentType = "application/json",
                    Description = "endpoint for Authorization Code and Implicit grants",
                    HttpVersion = Hummingbird.TestFramework.Services.HttpVersion.Version11,
                    OperationName = "Get_endpoint_for_Authorization_Code_and_Implicit_grants",
                    RequestType = typeof(Hummingbird.OAuth2Extension.OpenId_Connect.OpenId_Connect.Get_endpoint_for_Authorization_Code_and_Implicit_grants),
                    UriTemplate = "https://${OAuth2_Server}",
                    Path = "/oauth2/authorize",
                    ApplicationName = "OpenId Connect",
                    BodySerializer = Hummingbird.TestFramework.Serialization.AbstractSerializer.GetInstance(typeof(Hummingbird.TestFramework.Serialization.JsonSerializer)),
                    ServiceCategory = "OpenId Connect",
                    ServiceName = "",
                    
                },

                new HttpRequestMetadata(){
                    HttpMethod = HttpMethod.POST,
                    Id = new Guid("a5f9337d-6d11-b095-4510-6033f663fd43"),
                    ContentType = "application/x-www-form-urlencoded",
                    Description = "submit approval to authorization code or access token",
                    HttpVersion = Hummingbird.TestFramework.Services.HttpVersion.Version11,
                    OperationName = "Post_submit_approval_to_authorization_code_or_access_token",
                    RequestType = typeof(Hummingbird.OAuth2Extension.OpenId_Connect.OpenId_Connect.Post_submit_approval_to_authorization_code_or_access_token),
                    UriTemplate = "https://${OAuth2_Server}",
                    Path = "/oauth2/authorize",
                    ApplicationName = "OpenId Connect",
                    BodySerializer = Hummingbird.TestFramework.Serialization.AbstractSerializer.GetInstance(typeof(Hummingbird.TestFramework.Serialization.FormUrlEncodedSerializer)),
                    ServiceCategory = "OpenId Connect",
                    ServiceName = "",
                    
                },

                new HttpRequestMetadata(){
                    HttpMethod = HttpMethod.POST,
                    Id = new Guid("ef7bc56a-0ce2-7eab-a2d5-2c67fcedf5a2"),
                    ContentType = "application/x-www-form-urlencoded",
                    Description = "Request Access Tokens",
                    HttpVersion = Hummingbird.TestFramework.Services.HttpVersion.Version11,
                    OperationName = "Post_Request_Access_Tokens",
                    RequestType = typeof(Hummingbird.OAuth2Extension.OpenId_Connect.OpenId_Connect.Post_Request_Access_Tokens),
                    UriTemplate = "https://${OAuth2_Server}",
                    Path = "/oauth2/token",
                    ApplicationName = "OpenId Connect",
                    BodySerializer = Hummingbird.TestFramework.Serialization.AbstractSerializer.GetInstance(typeof(Hummingbird.TestFramework.Serialization.FormUrlEncodedSerializer)),
                    ServiceCategory = "OpenId Connect",
                    ServiceName = "",
                    ResponseType = typeof(Hummingbird.OAuth2Extension.OpenId_Connect.OpenId_Connect.Post_Request_Access_Tokens_200),

                },

                new HttpRequestMetadata(){
                    HttpMethod = HttpMethod.POST,
                    Id = new Guid("04465fe1-15ec-637c-0746-59632cf4b6ff"),
                    ContentType = "application/x-www-form-urlencoded",
                    Description = "Introspect a given access_token supported",
                    HttpVersion = Hummingbird.TestFramework.Services.HttpVersion.Version11,
                    OperationName = "Post_Introspect_a_given_access_token_supported",
                    RequestType = typeof(Hummingbird.OAuth2Extension.OpenId_Connect.OpenId_Connect.Post_Introspect_a_given_access_token_supported),
                    UriTemplate = "https://${OAuth2_Server}",
                    Path = "/oauth2/introspect",
                    ApplicationName = "OpenId Connect",
                    BodySerializer = Hummingbird.TestFramework.Serialization.AbstractSerializer.GetInstance(typeof(Hummingbird.TestFramework.Serialization.FormUrlEncodedSerializer)),
                    ServiceCategory = "OpenId Connect",
                    ServiceName = "",
                    ResponseType = typeof(Hummingbird.OAuth2Extension.OpenId_Connect.OpenId_Connect.Post_Introspect_a_given_access_token_supported_200),

                },

                new HttpRequestMetadata(){
                    HttpMethod = HttpMethod.GET,
                    Id = new Guid("1e9309c6-f217-e9d3-9e1a-ef2899ba458f"),
                    ContentType = "application/json",
                    Description = "Returns list of permission granted to the owner",
                    HttpVersion = Hummingbird.TestFramework.Services.HttpVersion.Version11,
                    OperationName = "Get_Returns_list_of_permission_granted_to_the_owner",
                    RequestType = typeof(Hummingbird.OAuth2Extension.OpenId_Connect.OpenId_Connect.Get_Returns_list_of_permission_granted_to_the_owner),
                    UriTemplate = "https://${OAuth2_Server}",
                    Path = "/oauth2/issued",
                    ApplicationName = "OpenId Connect",
                    BodySerializer = Hummingbird.TestFramework.Serialization.AbstractSerializer.GetInstance(typeof(Hummingbird.TestFramework.Serialization.JsonSerializer)),
                    ServiceCategory = "OpenId Connect",
                    ServiceName = "",
                    ResponseType = typeof(Hummingbird.OAuth2Extension.OpenId_Connect.OpenId_Connect.Get_Returns_list_of_permission_granted_to_the_owner_200),

                },

                new HttpRequestMetadata(){
                    HttpMethod = HttpMethod.DELETE,
                    Id = new Guid("166359bd-2169-a777-80a2-2bba595f55d2"),
                    ContentType = "application/json",
                    Description = "Revoke an application/client permission by the authorized owner",
                    HttpVersion = Hummingbird.TestFramework.Services.HttpVersion.Version11,
                    OperationName = "Delete_Revoke_an_applicationclient_permission_by_the_authorized_owner",
                    RequestType = typeof(Hummingbird.OAuth2Extension.OpenId_Connect.OpenId_Connect.Delete_Revoke_an_applicationclient_permission_by_the_authorized_owner),
                    UriTemplate = "https://${OAuth2_Server}",
                    Path = "/oauth2/issued",
                    ApplicationName = "OpenId Connect",
                    BodySerializer = Hummingbird.TestFramework.Serialization.AbstractSerializer.GetInstance(typeof(Hummingbird.TestFramework.Serialization.JsonSerializer)),
                    ServiceCategory = "OpenId Connect",
                    ServiceName = "",
                    
                },
				};
			}
		}

		public override HttpResponseMetadata[] HttpResponseServices
		{
			get
			{
	
				return new HttpResponseMetadata[]{

                new HttpResponseMetadata(){
                    HttpMethod = HttpMethod.GET,
                    ApplicationName = "OAuth2 Grant",
                    ServiceCategory = "Authorization Code",
                    ServiceName = "oauth2",
                    OperationName = "auth",
                    BodySerializer = Hummingbird.TestFramework.Serialization.AbstractSerializer.GetInstance(typeof(Hummingbird.TestFramework.Serialization.JsonSerializer)),
                    UriTemplate = "/auth",
                    ContentType = "application/json",
                    Id = new Guid("c765240b-901b-fa6c-5d01-0d07eee65018"),
                    Description = "Authentication Endpoint",
                    HttpVersion = Hummingbird.TestFramework.Services.HttpVersion.Version11,
                    RequestType = typeof(Hummingbird.OAuth2Extension.OAuth2_Grant.Authorization_Code.auth),
                    
                },

                new HttpResponseMetadata(){
                    HttpMethod = HttpMethod.POST,
                    ApplicationName = "OAuth2 Grant",
                    ServiceCategory = "Authorization Code",
                    ServiceName = "oauth2",
                    OperationName = "getToken",
                    BodySerializer = Hummingbird.TestFramework.Serialization.AbstractSerializer.GetInstance(typeof(Hummingbird.TestFramework.Serialization.FormUrlEncodedSerializer)),
                    UriTemplate = "/token",
                    ContentType = "application/x-www-form-urlencoded",
                    Id = new Guid("2ed6cb5d-4564-e4a4-3ea5-b4542c5d93ac"),
                    Description = "Request Access Token",
                    HttpVersion = Hummingbird.TestFramework.Services.HttpVersion.Version11,
                    RequestType = typeof(Hummingbird.OAuth2Extension.OAuth2_Grant.Authorization_Code.getToken),
                    
                },

                new HttpResponseMetadata(){
                    HttpMethod = HttpMethod.DELETE,
                    ApplicationName = "OAuth2 Grant",
                    ServiceCategory = "Authorization Code",
                    ServiceName = "oauth2",
                    OperationName = "deleteToken",
                    BodySerializer = Hummingbird.TestFramework.Serialization.AbstractSerializer.GetInstance(typeof(Hummingbird.TestFramework.Serialization.JsonSerializer)),
                    UriTemplate = "/token",
                    ContentType = "application/json",
                    Id = new Guid("17429120-ce5d-5fda-526e-28c782922cfe"),
                    Description = "Invalidate access token",
                    HttpVersion = Hummingbird.TestFramework.Services.HttpVersion.Version11,
                    RequestType = typeof(Hummingbird.OAuth2Extension.OAuth2_Grant.Authorization_Code.deleteToken),
                    
                },

                new HttpResponseMetadata(){
                    HttpMethod = HttpMethod.POST,
                    ApplicationName = "OAuth2 Grant",
                    ServiceCategory = "Client Credentials",
                    ServiceName = "Oauth2",
                    OperationName = "Post_Request_Access_Token",
                    BodySerializer = Hummingbird.TestFramework.Serialization.AbstractSerializer.GetInstance(typeof(Hummingbird.TestFramework.Serialization.FormUrlEncodedSerializer)),
                    UriTemplate = "/token",
                    ContentType = "application/x-www-form-urlencoded",
                    Id = new Guid("d6a851e0-29bd-99c0-5021-294a1e1072b7"),
                    Description = "Request Access Token",
                    HttpVersion = Hummingbird.TestFramework.Services.HttpVersion.Version11,
                    RequestType = typeof(Hummingbird.OAuth2Extension.OAuth2_Grant.Client_Credentials.Post_Request_Access_Token),
                    
                },

                new HttpResponseMetadata(){
                    HttpMethod = HttpMethod.DELETE,
                    ApplicationName = "OAuth2 Grant",
                    ServiceCategory = "Client Credentials",
                    ServiceName = "Oauth2",
                    OperationName = "Delete_Invalidate_access_token",
                    BodySerializer = Hummingbird.TestFramework.Serialization.AbstractSerializer.GetInstance(typeof(Hummingbird.TestFramework.Serialization.JsonSerializer)),
                    UriTemplate = "/token",
                    ContentType = "application/json",
                    Id = new Guid("5c4a445f-12cc-d3c6-eb2c-901165e5fa9d"),
                    Description = "Invalidate access token",
                    HttpVersion = Hummingbird.TestFramework.Services.HttpVersion.Version11,
                    RequestType = typeof(Hummingbird.OAuth2Extension.OAuth2_Grant.Client_Credentials.Delete_Invalidate_access_token),
                    
                },

                new HttpResponseMetadata(){
                    HttpMethod = HttpMethod.GET,
                    ApplicationName = "OpenId Connect",
                    ServiceCategory = "OpenId Connect",
                    ServiceName = "",
                    OperationName = "Get_endpoint_for_Authorization_Code_and_Implicit_grants",
                    BodySerializer = Hummingbird.TestFramework.Serialization.AbstractSerializer.GetInstance(typeof(Hummingbird.TestFramework.Serialization.JsonSerializer)),
                    UriTemplate = "/oauth2/authorize",
                    ContentType = "application/json",
                    Id = new Guid("38a53112-096a-4f04-cd80-7d6558329152"),
                    Description = "endpoint for Authorization Code and Implicit grants",
                    HttpVersion = Hummingbird.TestFramework.Services.HttpVersion.Version11,
                    RequestType = typeof(Hummingbird.OAuth2Extension.OpenId_Connect.OpenId_Connect.Get_endpoint_for_Authorization_Code_and_Implicit_grants),
                    
                },

                new HttpResponseMetadata(){
                    HttpMethod = HttpMethod.POST,
                    ApplicationName = "OpenId Connect",
                    ServiceCategory = "OpenId Connect",
                    ServiceName = "",
                    OperationName = "Post_submit_approval_to_authorization_code_or_access_token",
                    BodySerializer = Hummingbird.TestFramework.Serialization.AbstractSerializer.GetInstance(typeof(Hummingbird.TestFramework.Serialization.FormUrlEncodedSerializer)),
                    UriTemplate = "/oauth2/authorize",
                    ContentType = "application/x-www-form-urlencoded",
                    Id = new Guid("a9611341-6a7c-1a4b-a749-a93065514d5b"),
                    Description = "submit approval to authorization code or access token",
                    HttpVersion = Hummingbird.TestFramework.Services.HttpVersion.Version11,
                    RequestType = typeof(Hummingbird.OAuth2Extension.OpenId_Connect.OpenId_Connect.Post_submit_approval_to_authorization_code_or_access_token),
                    
                },

                new HttpResponseMetadata(){
                    HttpMethod = HttpMethod.POST,
                    ApplicationName = "OpenId Connect",
                    ServiceCategory = "OpenId Connect",
                    ServiceName = "",
                    OperationName = "Post_Request_Access_Tokens",
                    BodySerializer = Hummingbird.TestFramework.Serialization.AbstractSerializer.GetInstance(typeof(Hummingbird.TestFramework.Serialization.FormUrlEncodedSerializer)),
                    UriTemplate = "/oauth2/token",
                    ContentType = "application/x-www-form-urlencoded",
                    Id = new Guid("0d484464-0e18-389c-8ff9-2be20b162246"),
                    Description = "Request Access Tokens",
                    HttpVersion = Hummingbird.TestFramework.Services.HttpVersion.Version11,
                    RequestType = typeof(Hummingbird.OAuth2Extension.OpenId_Connect.OpenId_Connect.Post_Request_Access_Tokens),
                    ResponseType = typeof(Hummingbird.OAuth2Extension.OpenId_Connect.OpenId_Connect.Post_Request_Access_Tokens_200),

                },

                new HttpResponseMetadata(){
                    HttpMethod = HttpMethod.POST,
                    ApplicationName = "OpenId Connect",
                    ServiceCategory = "OpenId Connect",
                    ServiceName = "",
                    OperationName = "Post_Introspect_a_given_access_token_supported",
                    BodySerializer = Hummingbird.TestFramework.Serialization.AbstractSerializer.GetInstance(typeof(Hummingbird.TestFramework.Serialization.FormUrlEncodedSerializer)),
                    UriTemplate = "/oauth2/introspect",
                    ContentType = "application/x-www-form-urlencoded",
                    Id = new Guid("0b13d7e8-0918-a1c2-7fc0-fae2b08e52eb"),
                    Description = "Introspect a given access_token supported",
                    HttpVersion = Hummingbird.TestFramework.Services.HttpVersion.Version11,
                    RequestType = typeof(Hummingbird.OAuth2Extension.OpenId_Connect.OpenId_Connect.Post_Introspect_a_given_access_token_supported),
                    ResponseType = typeof(Hummingbird.OAuth2Extension.OpenId_Connect.OpenId_Connect.Post_Introspect_a_given_access_token_supported_200),

                },

                new HttpResponseMetadata(){
                    HttpMethod = HttpMethod.GET,
                    ApplicationName = "OpenId Connect",
                    ServiceCategory = "OpenId Connect",
                    ServiceName = "",
                    OperationName = "Get_Returns_list_of_permission_granted_to_the_owner",
                    BodySerializer = Hummingbird.TestFramework.Serialization.AbstractSerializer.GetInstance(typeof(Hummingbird.TestFramework.Serialization.JsonSerializer)),
                    UriTemplate = "/oauth2/issued",
                    ContentType = "application/json",
                    Id = new Guid("36e1a498-1318-ba1a-d3b4-64755125063a"),
                    Description = "Returns list of permission granted to the owner",
                    HttpVersion = Hummingbird.TestFramework.Services.HttpVersion.Version11,
                    RequestType = typeof(Hummingbird.OAuth2Extension.OpenId_Connect.OpenId_Connect.Get_Returns_list_of_permission_granted_to_the_owner),
                    ResponseType = typeof(Hummingbird.OAuth2Extension.OpenId_Connect.OpenId_Connect.Get_Returns_list_of_permission_granted_to_the_owner_200),

                },

                new HttpResponseMetadata(){
                    HttpMethod = HttpMethod.DELETE,
                    ApplicationName = "OpenId Connect",
                    ServiceCategory = "OpenId Connect",
                    ServiceName = "",
                    OperationName = "Delete_Revoke_an_applicationclient_permission_by_the_authorized_owner",
                    BodySerializer = Hummingbird.TestFramework.Serialization.AbstractSerializer.GetInstance(typeof(Hummingbird.TestFramework.Serialization.JsonSerializer)),
                    UriTemplate = "/oauth2/issued",
                    ContentType = "application/json",
                    Id = new Guid("1f237740-360c-b1fc-ff72-dbf6062e2bd9"),
                    Description = "Revoke an application/client permission by the authorized owner",
                    HttpVersion = Hummingbird.TestFramework.Services.HttpVersion.Version11,
                    RequestType = typeof(Hummingbird.OAuth2Extension.OpenId_Connect.OpenId_Connect.Delete_Revoke_an_applicationclient_permission_by_the_authorized_owner),
                    
                },
				};
			}
		}
			
        public override Parameter[] ServerParameters
        {
            get
            {
                return new Parameter[0];
            }
        }

        public override Parameter[] ClientParameters
        {
            get
            {
                return new Parameter[0];
            }
        }

	}
}
